FIND_PATH(EVENT_INCLUDE_DIR event.h /usr/include/ /usr/local/include/)

FIND_LIBRARY(EVENT_LIBRARY NAMES event PATH /usr/lib /usr/local/lib) 

IF(EVENT_INCLUDE_DIR AND EVENT_LIBRARY)
   SET(EVENT_FOUND TRUE)
ENDIF(EVENT_INCLUDE_DIR AND EVENT_LIBRARY)

IF(EVENT_FOUND)
   IF(NOT EVENT_FIND_QUIETLY)
      MESSAGE(STATUS "Found EVENT: ${EVENT_LIBRARY}")
   ENDIF(NOT EVENT_FIND_QUIETLY)
ELSE(EVENT_FOUND)
   IF(EVENT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find EVENT")
   ENDIF(EVENT_FIND_REQUIRED)
ENDIF(EVENT_FOUND)

